In [2]:
#numpy array

my_list = [1,2,3,4,5,6]

np.array(my_list)


NameError: name 'np' is not defined

In [23]:
#numpy array
import numpy as np
my_list = [1,2,3,4,5,6]

arr=np.array(my_list)


In [5]:
arr

array([1, 2, 3, 4, 5, 6])

In [8]:
#2d array


my_list_2d = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
my_list_2d

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
arr_2d= np.array(my_list_2d)
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
#arrange function
newarr = arr.reshape(4, 3)   #one dimentional array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
arr1 = np.arange(0,10) #step size

In [41]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr1.shape

(4,)

In [26]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [38]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2,3,2)

In [39]:
newarr


array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [62]:
arr2 = np.arange(10) #step size
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
newarr = arr2.reshape(5,2)

In [54]:
newarr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [55]:
newarr.dtype

dtype('int32')

In [65]:
#accessing
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
arr2[0]

0

In [67]:
arr2[2]

2

In [68]:
arr2[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
arr2[:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [77]:
arr2[-9:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
arr2[:-9]

array([0])

In [81]:
arr2[:-9]

array([0])

In [86]:
random_arr = np.random.rand(2,2)

In [87]:
c

array([[0.79080666, 0.64901611],
       [0.50894029, 0.51263892]])

In [93]:
random_arr = np.random.randint(2,10)

In [94]:
random_arr

8

In [97]:
random_arr2 = np.random.randn(2,4)

In [98]:
random_arr2 

array([[ 1.11855753,  0.75014517,  0.65914133,  1.0344387 ],
       [-0.80182933, -1.14833554,  0.58465689, -0.32162809]])

In [101]:
#ones

np.ones(5)

array([1., 1., 1., 1., 1.])

In [102]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [103]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [104]:
my_2d = [[1,2,3],[4,5,6],[7,8,9]]

In [105]:
my_2d

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [108]:
arr_new = np.array(my_2d)

In [114]:
arr_2d[0][2]   #single bracket access

3

In [115]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [116]:
arr_2d[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [123]:
arr_2d[0:1]

array([[1, 2, 3]])

In [124]:
arr_2d[:-1]

array([[1, 2, 3],
       [4, 5, 6]])

In [140]:
arr_2d[1:,1:]

array([[5, 6],
       [8, 9]])

In [141]:
arr_2d[0:2,1:]

array([[2, 3],
       [5, 6]])

In [144]:
#universal function

In [146]:
arr4 = np.arrange(5)

AttributeError: module 'numpy' has no attribute 'arrange'

In [148]:
arr5 = np.arange(10)
arr5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [149]:
arr5.max()

9

In [152]:
arr5.mean()

4.5

In [153]:
arr5.min()

0

In [154]:
arr5 + arr5

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [155]:
arr5 - arr5

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [156]:
arr5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [157]:
np.min(arr5)

0

In [158]:
np.max(arr5)

9

In [159]:
np.mean(arr5)

4.5

In [160]:
arr6 = arr5[0:5]

In [161]:
arr6

array([0, 1, 2, 3, 4])

In [162]:
arr5[0:5] =100

In [163]:
arr5

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [165]:
arr5 **2

array([10000, 10000, 10000, 10000, 10000,    25,    36,    49,    64,
          81], dtype=int32)

In [166]:
np.sin(arr5)

array([-0.50636564, -0.50636564, -0.50636564, -0.50636564, -0.50636564,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [167]:
np.log(arr5)

array([4.60517019, 4.60517019, 4.60517019, 4.60517019, 4.60517019,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [169]:
np.linspace(0, 10, 5)  #evenly spaced 

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [29]:
import time
from sys import getsizeof
#from timeit import timeit

In [28]:
start = time.process_time()
start

181.546875

In [24]:
np.linspace(0, 10, 5)
time = time.process_time()-start
print(time)

0.625


In [32]:
list1 =[1,2,3,45,6,6]
list1


[1, 2, 3, 45, 6, 6]

In [33]:
getsizeof(list1)

104

In [34]:
a = "HI THERE"
a

'HI THERE'